#filename: prometheus.yml

global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'snmp-servers'
    metrics_path: /snmp

    params:
      module: [system]
      auth: [public_v2c]

    static_configs:
      - targets:
          - localhost

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9116

  - job_name: "sql_exporter"
    scrape_interval: 15s
    static_configs:
      - targets:
          - "localhost:9399"
